services:
  postgres:
    image: postgres:14
    container_name: lunaroja_db
    restart: always
    environment:
      POSTGRES_USER: lunaroja
      POSTGRES_PASSWORD: lunaroja123
      POSTGRES_DB: lunaroja
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lunaroja_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: lunaroja_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lunaroja.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - lunaroja_net

  backend:
    build: ./backend
    container_name: lunaroja_backend
    env_file:
      - .env   # carga EMAIL_PASS, JWT_SECRET, etc.
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: lunaroja
      DB_PASSWORD: lunaroja123
      DB_NAME: lunaroja
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres
      - libretranslate
    volumes:
      - uploads_data:/app/uploads
    networks:
      - lunaroja_net

  frontend:
    build: ./frontend
    container_name: lunaroja_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - lunaroja_net

  libretranslate:
    image: libretranslate/libretranslate:v1.5.0
    container_name: lunaroja_libretranslate
    restart: always
    user: root
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=es,en,ar
      - LT_UPDATE_MODELS=false
    volumes:
      - libretranslate_data:/home/libretranslate/.local/share
    networks:
      - lunaroja_net

volumes:
  postgres_data:
    name: lunaroja_postgres_data
  uploads_data:
    name: lunaroja_uploads_data
  libretranslate_data:

networks:
  lunaroja_net:
    driver: bridge